"""empty message

Revision ID: a5f9fefc36cb
Revises: df4817b80902
Create Date: 2022-11-14 18:27:40.493769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5f9fefc36cb'
down_revision = 'df4817b80902'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('referees', sa.Column('leagues_registered', sa.Integer(), nullable=True))
    op.drop_constraint('referees_leagues_registered_fkey', 'referees', type_='foreignkey')
    op.create_foreign_key(None, 'referees', 'leagues', ['leagues_registered'], ['id'])
    op.drop_column('referees', 'league_registered')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('referees', sa.Column('league_registered', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'referees', type_='foreignkey')
    op.create_foreign_key('referees_leagues_registered_fkey', 'referees', 'leagues', ['league_registered'], ['id'])
    op.drop_column('referees', 'leagues_registered')
    # ### end Alembic commands ###
