"""empty message

Revision ID: 9e3642368ea3
Revises: 567e8e26fbf9
Create Date: 2022-11-11 13:51:36.591677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e3642368ea3'
down_revision = '567e8e26fbf9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games.referee',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('referee_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['referee_id'], ['referees.id'], ),
    sa.PrimaryKeyConstraint('game_id', 'referee_id')
    )
    op.create_table('games.stadiums',
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('stadium_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['stadium_id'], ['stadiums.id'], ),
    sa.PrimaryKeyConstraint('game_id', 'stadium_id')
    )
    op.create_table('teams.games',
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('team_id', 'game_id')
    )
    op.drop_table('teams_games')
    op.drop_constraint('fk_league', 'games', type_='foreignkey')
    op.drop_constraint('fk_referee', 'games', type_='foreignkey')
    op.drop_constraint('fk_stadiums', 'games', type_='foreignkey')
    op.create_foreign_key(None, 'games', 'leagues', ['league'], ['id'])
    op.create_foreign_key(None, 'games', 'teams', ['home_team'], ['id'])
    op.create_foreign_key(None, 'games', 'teams', ['away_team'], ['id'])
    op.create_foreign_key(None, 'games', 'stadiums', ['stadium'], ['id'])
    op.create_foreign_key(None, 'games', 'referees', ['referee'], ['id'])
    op.drop_constraint('fk_nations_teams', 'nations', type_='foreignkey')
    op.create_foreign_key(None, 'nations', 'teams', ['national_team'], ['id'])
    op.drop_constraint('fk_team_id', 'player_teams', type_='foreignkey')
    op.drop_constraint('fk_player_id', 'player_teams', type_='foreignkey')
    op.create_foreign_key(None, 'player_teams', 'teams', ['team_id'], ['id'])
    op.create_foreign_key(None, 'player_teams', 'players', ['player_id'], ['id'])
    op.alter_column('players', 'committed_nation',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('players', 'club_team',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('players', 'national_team',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('fk_nation', 'players', type_='foreignkey')
    op.drop_constraint('fk_club_team', 'players', type_='foreignkey')
    op.drop_constraint('fk_national_team', 'players', type_='foreignkey')
    op.create_foreign_key(None, 'players', 'nations', ['committed_nation'], ['id'])
    op.create_foreign_key(None, 'players', 'teams', ['national_team'], ['id'])
    op.create_foreign_key(None, 'players', 'teams', ['club_team'], ['id'])
    op.drop_constraint('fk_leagues_registered', 'referees', type_='foreignkey')
    op.create_foreign_key(None, 'referees', 'leagues', ['leagues_registered'], ['id'])
    op.add_column('stadiums', sa.Column('max_capacity', sa.Integer(), nullable=True))
    op.alter_column('stadiums', 'city',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_constraint('fk_nation', 'stadiums', type_='foreignkey')
    op.create_foreign_key(None, 'stadiums', 'nations', ['nation'], ['id'])
    op.drop_column('stadiums', 'max_capcity')
    op.alter_column('teams', 'home_stadium',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('fk_stadiums', 'teams', type_='foreignkey')
    op.create_foreign_key(None, 'teams', 'stadiums', ['home_stadium'], ['id'])
    op.drop_constraint('fk_team_id', 'teams_leagues', type_='foreignkey')
    op.drop_constraint('fk_league_id', 'teams_leagues', type_='foreignkey')
    op.create_foreign_key(None, 'teams_leagues', 'teams', ['team_id'], ['id'])
    op.create_foreign_key(None, 'teams_leagues', 'leagues', ['league_id'], ['id'])
    op.add_column('teams_stadiums', sa.Column('team_id', sa.Integer(), nullable=False))
    op.drop_constraint('fk_stadium_id', 'teams_stadiums', type_='foreignkey')
    op.drop_constraint('fk_teams_id', 'teams_stadiums', type_='foreignkey')
    op.create_foreign_key(None, 'teams_stadiums', 'teams', ['team_id'], ['id'])
    op.create_foreign_key(None, 'teams_stadiums', 'stadiums', ['stadium_id'], ['id'])
    op.drop_column('teams_stadiums', 'teams_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams_stadiums', sa.Column('teams_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'teams_stadiums', type_='foreignkey')
    op.drop_constraint(None, 'teams_stadiums', type_='foreignkey')
    op.create_foreign_key('fk_teams_id', 'teams_stadiums', 'teams', ['teams_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_stadium_id', 'teams_stadiums', 'stadiums', ['stadium_id'], ['id'], ondelete='SET NULL')
    op.drop_column('teams_stadiums', 'team_id')
    op.drop_constraint(None, 'teams_leagues', type_='foreignkey')
    op.drop_constraint(None, 'teams_leagues', type_='foreignkey')
    op.create_foreign_key('fk_league_id', 'teams_leagues', 'leagues', ['league_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_team_id', 'teams_leagues', 'teams', ['team_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'teams', type_='foreignkey')
    op.create_foreign_key('fk_stadiums', 'teams', 'stadiums', ['home_stadium'], ['id'], ondelete='SET NULL')
    op.alter_column('teams', 'home_stadium',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('stadiums', sa.Column('max_capcity', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'stadiums', type_='foreignkey')
    op.create_foreign_key('fk_nation', 'stadiums', 'nations', ['nation'], ['id'], ondelete='SET NULL')
    op.alter_column('stadiums', 'city',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('stadiums', 'max_capacity')
    op.drop_constraint(None, 'referees', type_='foreignkey')
    op.create_foreign_key('fk_leagues_registered', 'referees', 'leagues', ['leagues_registered'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'players', type_='foreignkey')
    op.drop_constraint(None, 'players', type_='foreignkey')
    op.drop_constraint(None, 'players', type_='foreignkey')
    op.create_foreign_key('fk_national_team', 'players', 'teams', ['national_team'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_club_team', 'players', 'teams', ['club_team'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_nation', 'players', 'nations', ['committed_nation'], ['id'], ondelete='SET NULL')
    op.alter_column('players', 'national_team',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('players', 'club_team',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('players', 'committed_nation',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'player_teams', type_='foreignkey')
    op.drop_constraint(None, 'player_teams', type_='foreignkey')
    op.create_foreign_key('fk_player_id', 'player_teams', 'players', ['player_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_team_id', 'player_teams', 'teams', ['team_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'nations', type_='foreignkey')
    op.create_foreign_key('fk_nations_teams', 'nations', 'teams', ['national_team'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'games', type_='foreignkey')
    op.drop_constraint(None, 'games', type_='foreignkey')
    op.drop_constraint(None, 'games', type_='foreignkey')
    op.drop_constraint(None, 'games', type_='foreignkey')
    op.drop_constraint(None, 'games', type_='foreignkey')
    op.create_foreign_key('fk_stadiums', 'games', 'stadiums', ['stadium'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_referee', 'games', 'referees', ['referee'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_league', 'games', 'leagues', ['league'], ['id'], ondelete='SET NULL')
    op.create_table('teams_games',
    sa.Column('games_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('home_team_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('away_team_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.id'], name='fk_away_team_id', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['games_id'], ['games.id'], name='fk_games_id', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.id'], name='fk_home_team_id', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('games_id', 'home_team_id', 'away_team_id', name='teams_games_pkey')
    )
    op.drop_table('teams.games')
    op.drop_table('games.stadiums')
    op.drop_table('games.referee')
    # ### end Alembic commands ###
